// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWTH054fA0hDBJfkLblx-YSjN6mi14Rk0',
    appId: '1:568757808004:web:a9449648bcf7f9bf1acbd1',
    messagingSenderId: '568757808004',
    projectId: 'realestateapp-8a09a',
    authDomain: 'realestateapp-8a09a.firebaseapp.com',
    storageBucket: 'realestateapp-8a09a.firebasestorage.app',
    measurementId: 'G-Q02E3JW02C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0v-zSi5BYRIwz00FWTjGpaWwSSjjAIjE',
    appId: '1:568757808004:android:04f21a6b2c40c1c31acbd1',
    messagingSenderId: '568757808004',
    projectId: 'realestateapp-8a09a',
    storageBucket: 'realestateapp-8a09a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7KQlgoRTMQW9RsYu5y591aTREMxtbc14',
    appId: '1:568757808004:ios:7bc00fab0aa8edb21acbd1',
    messagingSenderId: '568757808004',
    projectId: 'realestateapp-8a09a',
    storageBucket: 'realestateapp-8a09a.firebasestorage.app',
    iosBundleId: 'com.example.realEstateApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7KQlgoRTMQW9RsYu5y591aTREMxtbc14',
    appId: '1:568757808004:ios:7bc00fab0aa8edb21acbd1',
    messagingSenderId: '568757808004',
    projectId: 'realestateapp-8a09a',
    storageBucket: 'realestateapp-8a09a.firebasestorage.app',
    iosBundleId: 'com.example.realEstateApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWTH054fA0hDBJfkLblx-YSjN6mi14Rk0',
    appId: '1:568757808004:web:49b2cee46b4f67551acbd1',
    messagingSenderId: '568757808004',
    projectId: 'realestateapp-8a09a',
    authDomain: 'realestateapp-8a09a.firebaseapp.com',
    storageBucket: 'realestateapp-8a09a.firebasestorage.app',
    measurementId: 'G-Y4EV9PV7EQ',
  );
}
